// DO NOT EDIT. generated by github.com/tinywasm/orm

package appointmentbooking

import (
	"github.com/tinywasm/fmt"
	"github.com/tinywasm/orm"
)

func (m *EmployeeServiceConfig) TableName() string {
	return "employee_service_config"
}

func (m *EmployeeServiceConfig) FormName() string {
	return "employee_service_config"
}

var _schemaEmployeeServiceConfig = []fmt.Field{
		{Name: "id", Type: fmt.FieldText, PK: true},
		{Name: "tenant_id", Type: fmt.FieldText},
		{Name: "staff_id", Type: fmt.FieldText},
		{Name: "service_id", Type: fmt.FieldText},
		{Name: "duration_min", Type: fmt.FieldInt},
		{Name: "buffer_min", Type: fmt.FieldInt},
		{Name: "price_override", Type: fmt.FieldFloat},
		{Name: "payment_required", Type: fmt.FieldBool},
		{Name: "is_active", Type: fmt.FieldBool},
	}

func (m *EmployeeServiceConfig) Schema() []fmt.Field { return _schemaEmployeeServiceConfig }

func (m *EmployeeServiceConfig) Pointers() []any {
	return []any{
		&m.ID,
		&m.TenantID,
		&m.StaffID,
		&m.ServiceID,
		&m.DurationMin,
		&m.BufferMin,
		&m.PriceOverride,
		&m.PaymentRequired,
		&m.IsActive,
	}
}

var EmployeeServiceConfig_ = struct {
	TableName string
	ID string
	TenantID string
	StaffID string
	ServiceID string
	DurationMin string
	BufferMin string
	PriceOverride string
	PaymentRequired string
	IsActive string
}{
	TableName: "employee_service_config",
	ID: "id",
	TenantID: "tenant_id",
	StaffID: "staff_id",
	ServiceID: "service_id",
	DurationMin: "duration_min",
	BufferMin: "buffer_min",
	PriceOverride: "price_override",
	PaymentRequired: "payment_required",
	IsActive: "is_active",
}

func ReadOneEmployeeServiceConfig(qb *orm.QB, model *EmployeeServiceConfig) (*EmployeeServiceConfig, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllEmployeeServiceConfig(qb *orm.QB) ([]*EmployeeServiceConfig, error) {
	var results []*EmployeeServiceConfig
	err := qb.ReadAll(
		func() orm.Model { return &EmployeeServiceConfig{} },
		func(m orm.Model) { results = append(results, m.(*EmployeeServiceConfig)) },
	)
	return results, err
}

func (m *WorkCalendarConfig) TableName() string {
	return "work_calendar_config"
}

func (m *WorkCalendarConfig) FormName() string {
	return "work_calendar_config"
}

var _schemaWorkCalendarConfig = []fmt.Field{
		{Name: "id", Type: fmt.FieldText, PK: true},
		{Name: "tenant_id", Type: fmt.FieldText},
		{Name: "staff_id", Type: fmt.FieldText},
		{Name: "timezone", Type: fmt.FieldText},
		{Name: "is_active", Type: fmt.FieldBool},
	}

func (m *WorkCalendarConfig) Schema() []fmt.Field { return _schemaWorkCalendarConfig }

func (m *WorkCalendarConfig) Pointers() []any {
	return []any{
		&m.ID,
		&m.TenantID,
		&m.StaffID,
		&m.Timezone,
		&m.IsActive,
	}
}

var WorkCalendarConfig_ = struct {
	TableName string
	ID string
	TenantID string
	StaffID string
	Timezone string
	IsActive string
}{
	TableName: "work_calendar_config",
	ID: "id",
	TenantID: "tenant_id",
	StaffID: "staff_id",
	Timezone: "timezone",
	IsActive: "is_active",
}

func ReadOneWorkCalendarConfig(qb *orm.QB, model *WorkCalendarConfig) (*WorkCalendarConfig, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllWorkCalendarConfig(qb *orm.QB) ([]*WorkCalendarConfig, error) {
	var results []*WorkCalendarConfig
	err := qb.ReadAll(
		func() orm.Model { return &WorkCalendarConfig{} },
		func(m orm.Model) { results = append(results, m.(*WorkCalendarConfig)) },
	)
	return results, err
}

func (m *WorkCalendarWeekly) TableName() string {
	return "work_calendar_weekly"
}

func (m *WorkCalendarWeekly) FormName() string {
	return "work_calendar_weekly"
}

var _schemaWorkCalendarWeekly = []fmt.Field{
		{Name: "id", Type: fmt.FieldText, PK: true},
		{Name: "tenant_id", Type: fmt.FieldText},
		{Name: "staff_id", Type: fmt.FieldText},
		{Name: "day_of_week", Type: fmt.FieldInt},
		{Name: "work_start", Type: fmt.FieldInt},
		{Name: "work_finish", Type: fmt.FieldInt},
		{Name: "break_start", Type: fmt.FieldInt},
		{Name: "break_finish", Type: fmt.FieldInt},
		{Name: "is_active", Type: fmt.FieldBool},
	}

func (m *WorkCalendarWeekly) Schema() []fmt.Field { return _schemaWorkCalendarWeekly }

func (m *WorkCalendarWeekly) Pointers() []any {
	return []any{
		&m.ID,
		&m.TenantID,
		&m.StaffID,
		&m.DayOfWeek,
		&m.WorkStart,
		&m.WorkFinish,
		&m.BreakStart,
		&m.BreakFinish,
		&m.IsActive,
	}
}

var WorkCalendarWeekly_ = struct {
	TableName string
	ID string
	TenantID string
	StaffID string
	DayOfWeek string
	WorkStart string
	WorkFinish string
	BreakStart string
	BreakFinish string
	IsActive string
}{
	TableName: "work_calendar_weekly",
	ID: "id",
	TenantID: "tenant_id",
	StaffID: "staff_id",
	DayOfWeek: "day_of_week",
	WorkStart: "work_start",
	WorkFinish: "work_finish",
	BreakStart: "break_start",
	BreakFinish: "break_finish",
	IsActive: "is_active",
}

func ReadOneWorkCalendarWeekly(qb *orm.QB, model *WorkCalendarWeekly) (*WorkCalendarWeekly, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllWorkCalendarWeekly(qb *orm.QB) ([]*WorkCalendarWeekly, error) {
	var results []*WorkCalendarWeekly
	err := qb.ReadAll(
		func() orm.Model { return &WorkCalendarWeekly{} },
		func(m orm.Model) { results = append(results, m.(*WorkCalendarWeekly)) },
	)
	return results, err
}

func (m *WorkCalendarException) TableName() string {
	return "work_calendar_exception"
}

func (m *WorkCalendarException) FormName() string {
	return "work_calendar_exception"
}

var _schemaWorkCalendarException = []fmt.Field{
		{Name: "id", Type: fmt.FieldText, PK: true},
		{Name: "tenant_id", Type: fmt.FieldText},
		{Name: "staff_id", Type: fmt.FieldText},
		{Name: "specific_date", Type: fmt.FieldInt},
		{Name: "exception_type", Type: fmt.FieldText},
		{Name: "start_time", Type: fmt.FieldInt},
		{Name: "end_time", Type: fmt.FieldInt},
		{Name: "notes", Type: fmt.FieldText},
	}

func (m *WorkCalendarException) Schema() []fmt.Field { return _schemaWorkCalendarException }

func (m *WorkCalendarException) Pointers() []any {
	return []any{
		&m.ID,
		&m.TenantID,
		&m.StaffID,
		&m.SpecificDate,
		&m.ExceptionType,
		&m.StartTime,
		&m.EndTime,
		&m.Notes,
	}
}

var WorkCalendarException_ = struct {
	TableName string
	ID string
	TenantID string
	StaffID string
	SpecificDate string
	ExceptionType string
	StartTime string
	EndTime string
	Notes string
}{
	TableName: "work_calendar_exception",
	ID: "id",
	TenantID: "tenant_id",
	StaffID: "staff_id",
	SpecificDate: "specific_date",
	ExceptionType: "exception_type",
	StartTime: "start_time",
	EndTime: "end_time",
	Notes: "notes",
}

func ReadOneWorkCalendarException(qb *orm.QB, model *WorkCalendarException) (*WorkCalendarException, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllWorkCalendarException(qb *orm.QB) ([]*WorkCalendarException, error) {
	var results []*WorkCalendarException
	err := qb.ReadAll(
		func() orm.Model { return &WorkCalendarException{} },
		func(m orm.Model) { results = append(results, m.(*WorkCalendarException)) },
	)
	return results, err
}

func (m *Reservation) TableName() string {
	return "reservation"
}

func (m *Reservation) FormName() string {
	return "reservation"
}

var _schemaReservation = []fmt.Field{
		{Name: "id", Type: fmt.FieldText, PK: true},
		{Name: "tenant_id", Type: fmt.FieldText},
		{Name: "client_id", Type: fmt.FieldText},
		{Name: "creator_user_id", Type: fmt.FieldText},
		{Name: "employee_service_config_id", Type: fmt.FieldText},
		{Name: "staff_idsnapshot", Type: fmt.FieldText},
		{Name: "service_idsnapshot", Type: fmt.FieldText},
		{Name: "duration_min_snapshot", Type: fmt.FieldInt},
		{Name: "price_snapshot", Type: fmt.FieldFloat},
		{Name: "currency_snapshot", Type: fmt.FieldText},
		{Name: "reservation_date", Type: fmt.FieldInt},
		{Name: "reservation_time", Type: fmt.FieldInt},
		{Name: "local_string_date", Type: fmt.FieldText},
		{Name: "local_string_time", Type: fmt.FieldText},
		{Name: "status", Type: fmt.FieldText},
		{Name: "rescheduled_from_id", Type: fmt.FieldText},
		{Name: "payment_id", Type: fmt.FieldText},
		{Name: "notes", Type: fmt.FieldText},
		{Name: "updated_at", Type: fmt.FieldInt},
		{Name: "updated_by", Type: fmt.FieldText},
		{Name: "revision", Type: fmt.FieldInt},
	}

func (m *Reservation) Schema() []fmt.Field { return _schemaReservation }

func (m *Reservation) Pointers() []any {
	return []any{
		&m.ID,
		&m.TenantID,
		&m.ClientID,
		&m.CreatorUserID,
		&m.EmployeeServiceConfigID,
		&m.StaffIDSnapshot,
		&m.ServiceIDSnapshot,
		&m.DurationMinSnapshot,
		&m.PriceSnapshot,
		&m.CurrencySnapshot,
		&m.ReservationDate,
		&m.ReservationTime,
		&m.LocalStringDate,
		&m.LocalStringTime,
		&m.Status,
		&m.RescheduledFromID,
		&m.PaymentID,
		&m.Notes,
		&m.UpdatedAt,
		&m.UpdatedBy,
		&m.Revision,
	}
}

var Reservation_ = struct {
	TableName string
	ID string
	TenantID string
	ClientID string
	CreatorUserID string
	EmployeeServiceConfigID string
	StaffIDSnapshot string
	ServiceIDSnapshot string
	DurationMinSnapshot string
	PriceSnapshot string
	CurrencySnapshot string
	ReservationDate string
	ReservationTime string
	LocalStringDate string
	LocalStringTime string
	Status string
	RescheduledFromID string
	PaymentID string
	Notes string
	UpdatedAt string
	UpdatedBy string
	Revision string
}{
	TableName: "reservation",
	ID: "id",
	TenantID: "tenant_id",
	ClientID: "client_id",
	CreatorUserID: "creator_user_id",
	EmployeeServiceConfigID: "employee_service_config_id",
	StaffIDSnapshot: "staff_idsnapshot",
	ServiceIDSnapshot: "service_idsnapshot",
	DurationMinSnapshot: "duration_min_snapshot",
	PriceSnapshot: "price_snapshot",
	CurrencySnapshot: "currency_snapshot",
	ReservationDate: "reservation_date",
	ReservationTime: "reservation_time",
	LocalStringDate: "local_string_date",
	LocalStringTime: "local_string_time",
	Status: "status",
	RescheduledFromID: "rescheduled_from_id",
	PaymentID: "payment_id",
	Notes: "notes",
	UpdatedAt: "updated_at",
	UpdatedBy: "updated_by",
	Revision: "revision",
}

func ReadOneReservation(qb *orm.QB, model *Reservation) (*Reservation, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllReservation(qb *orm.QB) ([]*Reservation, error) {
	var results []*Reservation
	err := qb.ReadAll(
		func() orm.Model { return &Reservation{} },
		func(m orm.Model) { results = append(results, m.(*Reservation)) },
	)
	return results, err
}
